class InstantiateCSVError(Exception):
    """Класс исключения при поврежденном файле"""
    pass
